### ISSUE TITLE
tracking issues and canonical repository

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/exchange#1]
I suggest to delete https://github.com/openvocab/exchange and transfer this repository to openvocab organization. Assuming that you want canonical repository which tracks issues to stay there

**Comment by bhaugen** [comment]
Thanks. Is this better?

**Comment by elf-pavlik** [comment]
Yes, thank you!

**Comment by bhaugen** [comment]
Thank you! I was obviously ignorant about how to do some of this stuff.
