### ISSUE TITLE
Should we rename this repo?

### ISSUE THREAD

**Issue by bhaugen** [valueflows/exchange#10]
A bunch of concepts are related to Exchange:
- Intents (Offers and Wants) that may lead to exchanges
- Transfers (which may be one-way, not a reciprocal exchange)
- Ownership and other Agent:Resource relationships that may be affected by transfers
- Changes in Agent:Resource relationships that do not change ownership (e.g. custodian who has physical custody and responsibility but not ownership)

Is there a better name for this whole bundle?

**Comment by elf-pavlik** [comment]
> Ownership and other Agent:Resource relationships that may be affected by transfers

I would prefer to define _Transfer_ as **conceptual** change of ownership and don't conflate it with **physical** change of resource location _Transport_ or **virtual** change of resource location _MoveOfCurrencyBetweenAccounts_. Of course they all link to each other but each has distinct definition.

> Changes in Agent:Resource relationships that do not change ownership (e.g. custodian who has physical custody and responsibility but not ownership)

that sounds like going into modeling various aspects of **control** and **permissions**, one of possible approaches i recently mentioned in https://github.com/valueflows/agent/issues/54#issuecomment-150546795

**Comment by bhaugen** [comment]
Agreed about differentiating change of ownership from change of location.

**Comment by fosterlynn** [comment]
I have no need to change the name of the repo right now..... I think we want to keep process and exchange at the same level somehow.  But I also don't have any strong opinions, so I abstain.

Small note: the fact that we have economic events without a process and without an exchange doesn't bother me that much, they are still conceptually in the realm.

> Agreed about differentiating change of ownership from change of location.

I agree too.  Ha, I once did a gig at a gas utility, at the time they were de-regulated in the US.  The gas could change ownership 10 times in the same location in the pipeline, having absolutely nothing to do with anything operational.  All part of the money games of the 1%.

**Comment by elf-pavlik** [comment]
I remember we separated this repo from process, also to isolate all the concerns related to **accounting** https://github.com/valueflows/valueflows/issues/23

We also discussed tracking (logging) vs. accounting in https://github.com/valueflows/exchange/issues/8

IMO changes in ownership also fit accounting, only conceptual change, nothing at all changes in physical reality. If we isolate OwnershipTransfer from any physical aspects e.g. Transport 

Debt, Claim https://github.com/valueflows/exchange/issues/11 possibly also Commitment/Promise all don't have any physical presence, just concepts (of course related to our perception of what happens in physical reality), in many ways also specific to accounting...

Later we will get into modeling CurrencyTransfers ... virual/conceptual at least in case of monetary currencies, also accounting.

Maybe this repository would deal with all those conceptual aspects which don't happen in physical reality? Only records surface in computers and on paper but everything has purely conceptual nature...

(just dumping it here, now going to sleep and tomorrow and next days coding some agents related software)

**Comment by bhaugen** [comment]
@elf-pavlik I like the idea.

**Comment by elf-pavlik** [comment]
I think Commitment also could land here, it heavily depends on discussion in #14 

We also have this gdoc [Agent-Resource-Rights design space](https://docs.google.com/document/d/1PvuTYI9p_d6MovLY-3zFpkVRdv2fJXh5qcvIYlntcjY/edit) where we focus on **rights**.

Proposal rename this repo to **valueflows/right**

**Comment by fosterlynn** [comment]
> I think Commitment also could land here, it heavily depends on discussion in #14

You can have commitments in both transfer-land and process-land.  An example in process-land, "I commit to working on a knitted scarf this week, would you commit to help?".  In transfer-land, "I commit to giving Bob a knitted scarf (after we work on it) next week, then it will be his."

> We also have this gdoc Agent-Resource-Rights design space where we focus on rights.

I vote we get rid of this, and bring all relevant info back into github somewhere.  I find it too much extra motion to use another tool, especially getting all the right people together, who are already here; and storing the information in more than one place.  

> Proposal rename this repo to valueflows/right

I don't like Exchange any more either, although I'm still formulating how I think it should be structured.  But how about Transfer?  Or, why Right(s)?

**Comment by bhaugen** [comment]
Yes please ditch the google doc. It seemed helpful for about a day...

**Comment by elf-pavlik** [comment]
> You can have commitments in both transfer-land and process-land. An example in process-land, "I commit to working on a knitted scarf this week, would you commit to help?". In transfer-land, "I commit to giving Bob a knitted scarf (after we work on it) next week, then it will be his."

I think when we talk about Process we need to stay clear if we refer to Recipe, Plan or Reality/Report. Commitments seem not to play any role in Recipe part but only in Plan and Reality/Report.

As I mentioned in #14, one way of seeing commitment "I will work on knitting scarf for 20 hours next week" ~= transfer of rights to **consume** service ( a resource) - "elf knitting scarf for 20 hours next week". I don't say we should define it this way, just point out that Commitment seems in a domain of conceptual (mental) operations, where we deal with rights to resources and not direct operations on those physical/virtual (analogue/digital) resources.

**Comment by ahdinosaur** [comment]
> > Proposal rename this repo to valueflows/right
> 
> I don't like Exchange any more either, although I'm still formulating how I think it should be structured. But how about Transfer? Or, why Right(s)?

wondering the same, my intuition says we should rename this repo to `valueflows/transfer`.

**Comment by fosterlynn** [comment]
> wondering the same, my intuition says we should rename this repo to valueflows/transfer.

:+1:   although no need to be in a rush I suppose

**Comment by elf-pavlik** [comment]
> we should rename this repo to valueflows/transfer

:+1: i see it an improvement over exchange, if we later find out that we need more general term we can always rename it again

since no one objects @ahdinosaur would you like to rename it right away to `valueflows/transfer`?

**Comment by elf-pavlik** [comment]
Since we talk about rights, commitments, claims how about `valueflows/agreement`?
i bet @gcassel would like it :wink: 

everything here relates to sphere of our human perception, and especially man made concepts where we agree on something or not (claim, commitment, right), nothing happening directly in physical or virtual sphere (analogue/digital) but purely conceptual (mental) artifacts.

another species can observe that physical resource changed its location, or transformed from solid to liquid state. non other species can observe our claims, commitments and rights

**Comment by gcassel** [comment]
> Since we talk about rights, commitments, claims how about valueflows/agreement?
> i bet @gcassel would like it :wink:

Good mind-reading Elf...

Actually my main personal uncertainty is whether to advocate _communication_ or _agreement_ as a core VF vocab.    I guess that _agreement_ is a more practical focus, more tightly integrated with all other economic network issues here  (resources, agents, processes).

**Comment by gcassel** [comment]
^ on the other hand, it's not just about communicating for agreement IMO; it's also about **accounting** and data management.

For instance, one thing which struck me in McCarthy's (excellent) latest slides is that "Reality" isn't something we document... we deal with describing and accounting for perceived flows/events.  

Accounting isn't technically a subclass of communication; it's something else.  But I have a feeling you guys probably don't desire to have all these core vocabs:

resource
agent
process
communication
accounting

**Comment by bhaugen** [comment]
I think that all of the social/organizational/governmental/communication vocab and protocols are important and connected to the economic and accounting ones. But I also think we should be minimal here and partner with for example the w3c social groups to handle as much as possible.

I think we should start with intents and conversations for action as a bridge between the social and economic domains. @gcassel I am glad you are communing with us here and can help with crossing the bridges, but I don't think the VF vocab should stray too far into those other domains. And yes, it is a fuzzy boundary. I could be persuaded in either direction if it looks like it will work and make things easier rather than harder.

**Comment by ahdinosaur** [comment]
@elf-pavlik i was confused why Commitment (#21) is here, for me [i've been](https://github.com/valueflows/valueflows/blob/intro/README.md) distinguishing between ["what an agent can _do_ with resources"](https://github.com/valueflows/valueflows/issues/103) (Transfer, Transform / Process, Transport) and ["what an agent can _say_ about what they can do with resources"](https://github.com/valueflows/valueflows/issues/104) (Intent, Commitment / Plan, Event / Flow). to me, this makes more sense to anchor the major components of the vocab than a somewhat subjective separation between conceptual and virtual / physical.

**Comment by bhaugen** [comment]
I like @ahdinosaur 's distinctions here, although I think the dimensions of conceptual and physical are also useful. Maybe we figure out a multi-dimensional chart? The rubik's cube of value flows?

**Comment by elf-pavlik** [comment]
@ahdinosaur I take some time to dive deeper into how I understand your thinking. So far I see our takes on it complementing one another :smiley:

**Comment by ahdinosaur** [comment]
> So far I see our takes on it complementing one another :smiley:

same, cheers.

**Comment by elf-pavlik** [comment]
I think https://github.com/valueflows/intent/issues/5 supports considering `valueflows/intent` in context of `valueflows/exchange`. I start leaning toward proposed by @ahdinosaur 
- `valueflows/signal` https://github.com/valueflows/valueflows/issues/104
- `valueflows/action` https://github.com/valueflows/valueflows/issues/104

But let's take little more time to think over those various dimensions we want to distinguish...

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/exchange/-/issues/10.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
