### ISSUE TITLE
Gitter chat about transfers, ownership and related concepts, commitments and claims

### ISSUE THREAD

**Issue by bhaugen** [valueflows/exchange#11]
elf-pavlik 06:30
@bhaugen could you edit your comment with a reference to some more details? https://github.com/valueflows/agent/issues/54#issuecomment-150547526
elf-pavlik 06:32
thanks!
bhaugen 06:32
@elf-pavlik - Done. Unfortunately, we haven't done anything with the idea yet except to add a text box for people to write some access rules for a resource. They want something like a card reader that would turn the machine on if you had a card that allowed yoou to do so.
elf-pavlik 06:33
but that seems like only verb:use permission
if you want to verb:transfer the same resource, you need different permission, eg role:owner not role:planner
bhaugen 06:34
Have seen permissions for consume and transfer in business situations, too.
elf-pavlik 06:34
do you have example of transfer permission ?
bhaugen 06:36
Not documented, but a lot from experience. Often physical control: materials stored in a gated and locked fence, for example. Permission is granted by having the key.
elf-pavlik 06:37
permission to transfer ?
as change ownership of resource
WAC uses term 'modes of access' https://www.w3.org/wiki/WebAccessControl#Modes_of_Access
which in physical world would look like use, lend, transfer, repair etc.
bhaugen 06:38
Or in Vendor-Managed Inventory, companies sign agreements whereby a vendor stocks the other company's store shelves with their own products. The store never owns them, but can sell them to customers. Upon sale (with a bar code reading), the vendor is notified, and some of the selling price is due.
elf-pavlik 06:39
so role:technician have permission verb:repair
bhaugen 06:39
probably, but not always.
I've been a machine operator in situations where I repaired my own machine, and in others where other people did all the repair and I just ran the thing.
elf-pavlik 06:40
this vendor-managed inventory sounds like agent with role:owner delegates (grants) verb:transfer permission to another agent with role:broker or sth.
bhaugen 06:41
WAC looks like a good reference. Will study.
elf-pavlik 06:42
i will look at qualifying role based relationships between Resource -> Agent with permissions based on verbs use, repair, transfer, drive, lock etc.
bhaugen 06:43
Why don't you wait until we get the related processes worked out more.
elf-pavlik 06:43
on a web you pretty much have very simple case of read/write/update/delete (http verbs)
i don't say i will do it right now
and we already have BusTrip example with roles, which could just get few verbs and activities added on top of it
bhaugen 06:44
I am just guessing that those verbs will come up in process and transfer situations.
I don't yet buy the role idea.
elf-pavlik 06:44
for modeling Transfer, do you see any other verbs than transfer ?
bhaugen 06:45
I want to focus on what is actually happening before detuning to some simpler gloss over what happened.
elf-pavlik 06:45
I like it!
bhaugen 06:45
Transfer, however, is an economic event with a set of attributes and behaviors.
It is not just a plain verb.
likewise use.
Repair is a process.
elf-pavlik 06:46
just to clarify - by Transfer we only look at 'change of ownership' ?
bhaugen 06:51
as of now, that's what we mean
but we are not being careful yet about a bunch of related issues:
elf-pavlik 06:52
can we update diagrams to replace Exchange with Transfer? https://github.com/valueflows/valueflows#exchange-oriented-flow
bhaugen 06:53
We can. I also want to replace Event with Flow, which I think you wanted me to wait on before.
elf-pavlik 06:54
do you see 'Give Event' and 'Take Event' as different flows ?
or same flow looked at from two different perspectives ?
bhaugen 06:54
Enumerating issues related to transfer, that may not mean change of ownership: movement to a new location, change of custodian
same flow, different perspectives
elf-pavlik 06:54
only if we start conflating all kind of concepts under one overloaded terms
https://github.com/valueflows/agent/issues/38#issuecomment-150543678
bhaugen 06:55
if each agent keeps their own date stores, then each perspective will have a copy
elf-pavlik 06:56
Transfer 'change of ownership' may (or may not) have linked Transport 'change of physical location' for physical resources or CurrencyTransfer 'change of virtual location' for virtual resources
bhaugen 06:56
We do now conflate some of that stuff in our software. For the vocab, I would prefer to tease concepts apart more.
elf-pavlik 06:56
exactly!
bhaugen 06:57
At the same time, I think sweet spots exist.
As in, I'm fine sticking with Newtonian physics.
Quantum waves possibly not needed.
Which is to say, some level of precision is probably good enuf and more precision just gets more difficult to follow.
elf-pavlik 06:59
Do you see transfer work fitting https://github.com/valueflows/exchange repo?
bhaugen 06:59
And we will probably want some glosses over some details, e.g. role:driver which glosses over a lot of details of what is happening.
I am conflicted about the exchange repo and transfer.
exchange, transfer, offer, want, etc all go together.
might need a better name for the repo
elf-pavlik 07:00
transaction ?
bhaugen 07:00
no
as bad as event for overloading
elf-pavlik 07:01
true
bhaugen 07:01
ownership also goes in that bundle
elf-pavlik 07:02
yes, transfer pretty much deals exclusively with ownership and exchange with dependencies between transfers
bhaugen 07:02
i'll write up an issue in the exchange repo and see what everybody thinks
elf-pavlik 07:02

also intent (offer/want) also if succeed result in transfer (possibly exchange)
bhaugen 07:03
yes
elf-pavlik 07:04
BTW thinking about claim/debt we discussed yesterday, promise sounds like another possible term we could use
Repair is a process.
We could also see it as Service, which suggests that we can't consider it either-or Resource, Process
Or not, Service an input to Process..
bhaugen 07:08
Commitment is the same as Promise.
elf-pavlik 07:08
what makes it different from Claim ?
bhaugen 07:09
Claim is stronger than Commitment
elf-pavlik 07:09
stronger in a sense ?
bhaugen 07:09
Commitment promises to perform an economic event in the future.
Claim means that one commitment in a reciprocal pair has been fulfilled, and now the reciprocal event is due.
You can take unfilled claims to court.
Unfilled commitments are weaker.
elf-pavlik 07:10
hmmmm...
bhaugen 07:10
as in common breach-of-promise law
elf-pavlik 07:11
so commitment doesn't really commit
bhaugen 07:11
I'm not saying we should get into enforcing laws
commitment does commit if two agents have agreed on it.
But it's different if you have done your part, and I haven't
in reputation management, unfilled commitments are a down-rating
elf-pavlik 07:12
Sounds like it goes into Recipe, Plan, Reality distinciton
bhaugen 07:12
yes
elf-pavlik 07:12
Commitment - Plan , Claim - Reality
bhaugen 07:12
commitments are plans
pretty much
claims exist even if not materialized or reified
commitments don't
elf-pavlik 07:13
I didn't understand "claims exist even if not materialized or reified"
bhaugen 07:13
they need to be made explicit and agreed upon
In a pair of reciprocal commitments, if you do your part, my part is due
elf-pavlik 07:14
Claims seems like also needs an explicit agreement (before engaging in transfers)
bhaugen 07:14
you could reify it (checking my understanding again) by referring to your event which recorded doing your part
by pointing it out to me
or you could materialize it by sending me an invoice
claims depend on prior reciprocal commitments, and the fulfillment of one of the commitments
elf-pavlik 07:15
so in case of exchange
two sides make commitments of making transfers
bhaugen 07:16
yes
as in a customer/purchase order
elf-pavlik 07:16
on side fulfills their commitment and makes transfer
bhaugen 07:16
it's part of conversation for action
elf-pavlik 07:16
the other commitment turns into claim
bhaugen 07:16
offer-acceptance
https://en.wikipedia.org/wiki/Offer_and_acceptance
agree with your last two statements
elf-pavlik 07:18
so we need to have commitment first before we can have claim?
bhaugen 07:18
it's a good idea
elf-pavlik 07:19
how someone can make claim if other party didn't commit ?
bhaugen 07:19
but some actions imply reciprocal commitments
elf-pavlik 07:19
implicit commitments sound bit scary, can you please explain it on example ?
bhaugen 07:19
for example, at the farmers market, if I take some fruit out of the farmer's basket, the farmer expects me to pay
it's part of the set of common expectations of a physical marketplace
elf-pavlik 07:20
if you didn't agree with farmer first you pretty much stolen it
bhaugen 07:20
yup
elf-pavlik 07:20
if you agree you have commitment
bhaugen 07:20
but the farmer may offer free samples
in which case, I'm good as long as I take from free sample basket
elf-pavlik 07:21
so farmer agrees not to make any claims if someone takes them
bhaugen 07:21
yes
by means of a sign
or by handing me one
and saying free sample
elf-pavlik 07:21
so claims without commitments sound more like misunderstanding cases
bhaugen 07:22
situational
situations may cary expectations
elf-pavlik 07:22
so far you offered example based on misunderstanding
bhaugen 07:22
most people in the situation will have the same expectations
no, understanding
the farmer and I understand when I can take fruit without paying and when I cant
a child may not understand
elf-pavlik 07:23
you need to agree (make commitments)
bhaugen 07:23
but the agreements are cultural expectations of a situation
marketplaces are deep cross-culture
human social evolution
which we are now extending
re-evolving
in that situation, the commitments are implicit
elf-pavlik 07:24
can we try to find some clear example of claim which does not come from commitment - without misunderstanding, small children and other exceptional conditions
bhaugen 07:24
but exist nevertheless
no
elf-pavlik 07:25
so in general claims come out of commitments ?
bhaugen 07:25
yes
elf-pavlik 07:25
ok
bhaugen 07:25
but the commitments do not need to be explicit
that's mostly in physical marketplaces, though
elf-pavlik 07:25
example of not explicit commitment ?
bhaugen 07:25
farmers market
or any physical marketplace
common rules
everybody understands them
elf-pavlik 07:26
most people don't take goods away without asking person who brought them
bhaugen 07:26
adults anyway
that too
I don't borrow my neighbor's tools without explicit permission
but my neighbor may put an old chair on the curb with a free sign on it
elf-pavlik 07:27
do you see claim also a utility for cases of stealing ?
bhaugen 07:27
not sure I understand
elf-pavlik 07:27
no commitment but someone still claims claim
bhaugen 07:27
yes
based on property laws
and common law
and common cultural understanding
elf-pavlik 07:28
I see big difference between claims based on commitment and claims based on claims
bhaugen 07:28
shd we copy and past this into that issue I just posted?
don't understand claims based on claims
I think in the vocab we can stick to claims based on reciprocal commitments
elf-pavlik 07:29
i think he stolen apple from that tree, which i consider mine so he owes me, even that i didn't commit to offer anything or even recognized ownership claim of that person
bhaugen 07:29
and as you mentioned before, we need a different word for claim
elf-pavlik 07:30
and preferably use different term than claim
bhaugen 07:30
crisscrossed

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/exchange/-/issues/11.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
