### ISSUE TITLE
Use case: Rights as a resource in media?

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/exchange#13]
Starting this as a new issue, although there has already some discussion on rights as a resource sprinkled through issue #12 , which included many more broad ranging thoughts about transferring resources.

@gcassel I noticed in Hylo you mentioned that you have thought about rights in the context of art and media.  If you have the time and inclination, can you spell out how you think these might work for collaborative groups or in the context of people working towards the "next" economy?  

We think media would be a really good use case to think about rights as a resource to an underlying resource (the original media itself).  If this is too general a question, let's try to refine it.

**Comment by gcassel** [comment]
@fosterlynn , I think in often in terms of digital creative non-code media, which can be licensed in various ways (not perfectly) via http://creativecommons.org/     Their site states:

"CC licenses may be applied to any type of work, including educational resources, music, photographs, databases, government and public sector information, and many other types of material. The only categories of works for which CC does not recommend its licenses are computer software and hardware."

Obviously, there's a lot of focus on software in Value Flows and related groups...  however, I believe that CC type licenses are appropriate for much of the stuff which peer production communities and creative communities should care about.  For instance, any organizational models, essays, diagrams, flowcharts, studies, and all kinds of other (substantial, distinctive) media are automatically copyrighted, and can be openly licensed for use via CC type licenses.   

So, I'm thinking about a lot of stuff here other than what we normally think of as arts and entertainment media.   However, I do have a particular personal focus on arts and entertainment media.    

My neglected Open Intermedia Commons prototype considers the idea of community owned creative media commons, which could occur in online communities on any scale of (preferably fractal IMO) social organization.   This probably needs some serious updating, but it's available for general context and/or commenting:  https://docs.google.com/document/d/1e8MJUhsQUhRD4_xzepsoqBu4jX-nZYy7Pf2OqbCY--o/edit?usp=sharing

**Comment by dahacouk** [comment]
Please assign to @dahacouk

**Comment by bhaugen** [comment]
@dahacouk thanks - sent invitation to be VF member, then you or me or somebody can assign you to this issue.

Which should move it forward...maybe you and @gcassel can discuss.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/exchange/-/issues/13.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
