### ISSUE TITLE
Exchange definitions oriented towards coordination

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/exchange#17]
Ah, walks are so good for the thinking process!  Bob and I just did our walk'n'talk up and down the hill. :)

I hope this is a helpful thought.  Let's orient our definitions of all these REA concepts away from current relations of production towards new ones.  Immediately, let's get rid of the term "ownership" from the vocabulary.  

I think we can do this by making the definitions neutral and just recording what happens. The vocabulary has to work for transitional forms of exchange in all its range from selling on the market to non-market internal transfers between people collaborating on something.  Or paraphrasing what @elf-pavlik said somewhere, we need to know how many apples we can eat out of the pile without making someone else hungry or sad.

This is helpful for me, because I don't like having to spend all this time on exchange as it works for capitalists, because I'm trying to get beyond that.  But I do think that coordination, and in some cases very tight coordination, will be desirable for any foreseeable future of economic activity in a community or society. 

So, Transfer, the current focus.  How about instead of the focus on ownership, we focus on the functionality of the transfer.  Which is something like giving the receiving agent the ability to do whatever they want with that resource, like consume it in a process or transfer it to someone else.  It enables the resource to continue in a flow because some other agent now has the rights to consume, use, or transfer.  I think this should cover the most capitalist to the most post-capitalist transfer. 

I think some of the REA definitions that people use within that ontology community will be neutral already.  Others will need to be evolved.

So, thinking about some typical exchanges, let's see if we can make this work.  Here is a sale in the marketplace, with a transfer of a custom built computer with serial #1234 from agent A to agent B, and a reciprocal transfer of $1000 from agent B to agent A. Let's say that B sent the $1000 to A by bank transfer first.  I think the data that is created from that is: A transfer with a Give and Receive event, with the bank account resources decremented and incremented respectively.  That transfer of rights is done.  At the same time though, the computer is no longer available to A to sell or use, even though A still has it in possession.  So a transfer is also created for the computer.  This transfer has no events yet but should have a commitment to Give the computer to B.  When the computer is shipped, maybe A creates a Give event for the commitment.  When the computer is received, maybe B creates a Receive event.  There may be different points here where legally the ownership changes, governed by specific contractual stuff or policy.  But that doesn't have to be part of this recording of transfer data with commitments and events, I don't think.  There is also more complexity involving the shipping, which I'm ignoring to keep this simple, but which we should detail at some point because it is important to sorting this out.  But do we have everything we need to know here?  Can anyone define what they need to around ownership based on these facts on the ground?

What do you all think?

**Comment by gcassel** [comment]
I can't speak for anyone else  but I think we're probably closer to alignment now!

I'm not interested in the idea of "ownership" per se, but I think that permissions/ authorizations/ use-rights  are fundamentally important.   Maybe we get confused though because the use-rights to some virtual resources, such as a dollar figure in a bank account, seem to be almost entirely "embodied" by the digital location of those virtual resources-- and the transfer of use-rights seems to be embodied by the digital transfer of the virtual resources.  

Likewise, we implicitly perceive in most interactions that the use-rights of cash are embodied by possession of the cash.  It's not really true though...   for instance, I don't transfer cash to a shopkeeper simply because I lay some bills on a countertop.  IMO the actual transfer is a social agreement; a mutual understanding.  I.e., I'm probably transferring cash to a shopkeeper if I lay some bills on a countertop after some purchases have been added up, and I walk away after receiving a receipt and some change.  (Social agreements are often implicit, not explicit.)   

Hope this makes sense?   Sorry @elf-pavlik for the big focus on money, lol.

**Comment by gcassel** [comment]
^  My point is that as far as I can see, the most sustainable definition of transfer is focused entirely upon permissions/ use-rights, and not upon the transportation of any virtual or material resources.  (And maybe this could help with the issue of [synch/asynch](https://github.com/valueflows/exchange/issues/14#issue-140437196) transfer accounting.... reading that issue now

**Comment by danalexilewis** [comment]
Muddying up the waters a little: I think another factor of ownership is responsability. Not saying people actually fullfill/meet their responsibilities but never the less i think they exists. Eg A responsibility to maintain a thing (house) or decommission it correctly (battery).

So what could this look like:
1. inherited responsibilities. A receiver of an item inherits the responsibilities for it. I suppose you could say an item carries responsibilities with it. Eg Maintenance/decommisioning.
2. Added personal/social responsablites. Depending on where and through what vehicle you are operating than you may be bringing more responsibilities for the item to bare and possibly adding them to it. Eg safety, storage, compliance

Values could possibly follow a similar paradigm. Ie We attatch a social value to an item. Eg free trade. This is therefor a lart of the transaction. Also awarw this may accounted for somewhere else.

I am not sure if this really matters from a transactional point of view but I think it matters for next gen economy.

**Comment by danalexilewis** [comment]
My God android spell checking is shit - and you can't edit comments from mobile view... github fail

**Comment by bhaugen** [comment]
@agentlewis - We totally agree about responsibilities. @fosterlynn and I discussed that topic in our walk-n-talk that triggered this issue. Both rights and responsibilities. And it does matter from a transactional view. 

P.S. you can edit your github comments if you want...but I like responsablitzes.

**Comment by bhaugen** [comment]
I think this discussion would be improved if we followed @elf-pavlik 's admonition to use real-world examples. Before Lynn and I walked-and-talked about this and came to the realization that the word and concept of ownership should be banned from the vocabulary and we should get down to only what matters for coordination between humans, we and Pavlik played around with some examples in this very messy [google doc](https://docs.google.com/document/d/1PvuTYI9p_d6MovLY-3zFpkVRdv2fJXh5qcvIYlntcjY/edit?usp=sharing). Might be some that are worth harvesting, but it would be better to take actual examples from living situations. Most of those were generic.

**Comment by fosterlynn** [comment]
@agentlewis hey thanks much for pitching into the discussion, good thought about responsibilities, especially as we start to think of resources more collectively.

And it's ok, spelling is for wimps.... just kidding mom.....

**Comment by elf-pavlik** [comment]
responsibilities++

when we talk about permissions, we could try to evaluate ACL used by Solid for web resources - https://github.com/solid/web-access-control-spec

"access over ownership" ftw :wink:

**Comment by bhaugen** [comment]
I'd also like to take a look at capabilities, which I think have a bunch of advantages over ACLs.
[capabilities vs ACLs](https://www.google.com/#q=capabilities+vs+ACLs)

**Comment by gcassel** [comment]
rights/ permissions/ authorizations  and  responsibilities/ duties/ obligations  ....   I think those are all useful terms, and it'd probably okay to choose between alternative terms with pin-the-tail-on-the-donkey.  However, "rights and responsibilities" sounds good.

I guess that "permissions" sounds more neutral than "rights", which seems to have a moralistic "flavor" in some social contexts-- but that doesn't make it wrong to use "rights".   Maybe it's time to fight for **our** (version of) "rights"?

**Comment by bhaugen** [comment]
The main idea here, regardless of which words we use, is to define all this stuff in practical terms (where practicality might depend on the community).

**Comment by gcassel** [comment]
IMO practicality always depends on the community/ social context.  But I've personally decided to shelve the "permissions vs. rights" question for now, in decisive favor of "rights".  (switching to that term in Agreement-Based Organization right now.)  

If anyone doesn't love the term "rights" I'd like to hear about it here or elsewhere ;)

**Comment by elf-pavlik** [comment]
> Or paraphrasing what @elf-pavlik said somewhere, we need to know how many apples we can eat out of the pile without making someone else hungry or sad.

I need to turn transfers of ownership rights, allowing one to consume electricity, petrol etc. into use cases. I had some mind dumps on https://www.w3.org/community/webcurrencies/wiki/Assets_Shares which later made their way to the last paragraph of https://github.com/valueflows/valueflows/wiki/Principles-for-this-vocabulary

**Comment by fosterlynn** [comment]
:+1: asset shares use case.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/exchange/-/issues/17.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
