### ISSUE TITLE
Exchange chains / Network (Multi-Party) barter

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/exchange#19]
I have impression that most use cases focus on one-to-one exchange. I would like to make sure that we also include some use cases with chains of exchanges.

@tanius work(ed) on 
- http://edgeryders.eu/en/makerfox

and released some open source code at some point 
- http://edgeryders.eu/en/makerfox/open-sourcing-network-barter

they also did solid research and provided references
- http://edgeryders.eu/en/makerfox/background-for-multilateral-barter

**Comment by bhaugen** [comment]
That would be great! I looked at that a few times awhile ago. We want to be able to handle such use cases. Maybe @tanius could provide some?

We do have chains of exchanges in the DHen examples, but they are different from barter chains. Although barter chains are sorta related to mutual currency networks, and we can get a bunch of examples of those use cases from the Mutual Aid Networks.

**Comment by tanius** [comment]
Mmh I don't think chains of exchanges are a valuable concept, since:
- If the exchanges happen one after the other and independently of each other, they can be modelled as individual exchanges.
- If the exchanges happen at the same time and conditional on each other, they always form a loop, or a network of loops, because the "intermediate owners" of exchanged items do not have to be considered.

Let me know in which format / way I should provide use cases, if this is still relevant.

**Comment by fosterlynn** [comment]
Thanks @tanius !

I think we'll need to wait for @elf-pavlik to return so he can clarify what he was most interested in and respond to your comment.  

In terms of format, we are flexible.  What has been useful is to document the lowest level economic steps or occurrences.  Hmmm I found an "exchange chain" one by Pavlik here: https://github.com/valueflows/valueflows/blob/master/use-cases/exchange-chain.md.  There are others in that folder too, in various formats.

**Comment by elf-pavlik** [comment]
Hi @tanius 

> Mmh I don't think chains of exchanges are a valuable concept, since:
> - If the exchanges happen one after the other and independently of each other, they can be modelled as individual exchanges.

Not a case here! I look at exchanges which depend on one another.

> - If the exchanges happen at the same time and conditional on each other, they always form a loop, or a network of loops, because the "intermediate owners" of exchanged items do not have to be considered.

I would say that the agreement on particular chain of exchanges happens first - all parties confirm that they agree on a particular chain. Then one could say that resources already in 'legal' terms changed ownership and they just need delivery, one could also say that now each 'legal' owner has a _claim_ for the item still in possession of its previous (before the exchange) owner. For services it would work bit different since currently we only think of ownership and claims when discussing material items. 

> Let me know in which format / way I should provide use cases, if this is still relevant.

We just write .md files like https://github.com/valueflows/valueflows/blob/master/use-cases/exchange-chain.md If you would like to fork that repo and make PR we would really appreciate it. You can also publish them anywhere else on the web and share link with us.

**Comment by elf-pavlik** [comment]
Project shown in [this video](https://www.youtube.com/watch?v=Y_Td2_0rxYo) -- https://www.kidner-project.com/ had a chain of 30 kidney donors and 30 kidney recipients. I think this gives a nice example where no one wants to sell or buy (exchange for currency) any of those kidneys but pairs of donors and recipients search for matches of compatible kidneys.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/exchange/-/issues/19.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
