### ISSUE TITLE
define Claim

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/exchange#22]
similar to #21 based on https://github.com/valueflows/exchange/issues/14#issuecomment-216770713

> > as part of exchange where you have already consumed service of the other person (eg. got your car fixed)
> 
> In that case, you have a claim, which is stronger than a commitment. If you do your part of a set of reciprocal commitments, then you have a claim for the reciprocal event to happen.

**Comment by elf-pavlik** [comment]
claims play role only in cases of exchange, never in just transfer scenarios ([gitter chat](https://gitter.im/valueflows?at=572a27926871c4a646c1bfa7))

> @bhaugen 11:47
> Those are all a progression in strength of expectation for what will happen.

**Comment by elf-pavlik** [comment]
based on food networks case discussed in https://github.com/valueflows/resource/issues/14#issuecomment-217022939

When farmers 'sell' crops before they harvest them, they make commitment. When person who 'purchases' the crops makes reciprocal vf:Transfer, this commitment becomes a claim.

**Comment by elf-pavlik** [comment]
Thinking about Claim vs. Commitment. It seems that Claim has aspect of **debt**, which changes "You have promised me 5kg of apples" (Commitment) into "You owe me 5kg of apples" (Claim)

**Comment by elf-pavlik** [comment]
If we have situation with a claim for particular resource, for example a bicycle which we can identify with an IRI. I don't see clear difference between having a Claim and having ownership rights over that bike. It seems that once we have a Claim in place it can automatically turn into ownership rights. Once again physical location of the bike doesn't matter, it can for example always stay parked in shared bikeshed which both of agents, involved in the trasfer of ownership over that bike, use. This bikeshed also don't have parking places assigned to a person and one just puts a bike in any of available slots.

**Comment by bhaugen** [comment]
That, I think, is the position of Pavel Hruby and Christian Scheller in this email thread:

From me to Pavel:

> Followup questions about your POA article,"Business Process and Value Delivery Modeling Using Possession, Ownership and Availability (POA) in Enterprises and Business Networks".
> 
> Possession vs Custody:
> 
> Use case: vendor-managed inventory. The inventory is in the custody of
> the seller (usually a retail store), but the vendor owns it until the
> retailer sells it, at which time it passes briefly through the
> retailer's accounts and most of the purchase price flows back to the
> vendor.
> 
> Does the retailer have Possession in the POA model? In the retailer's
> accounting system, the vendor-managed inventory will not appear as
> Assets. It's more like Availability in the POA model (I think).
> But the retailer has physical possession, and the retailer's Custodian
> responsibilities might include liability for theft and damage.
> 
> Use case: transportation. A purchased item gets loaded onto a truck
> for delivery. The trucking company now has custody. Depending on
> whether it's FOB Shipping Point or FOB Destination, either the buyer
> or the seller has ownership. The trucking company, or the owner, may
> be liable for loss or damage, and may have insurance to cover it.
> 
> The seller does not have possession anymore, and the buyer does not
> have possession yet. Does the trucking company have possession?

From Pavel to me:

> The answer is yes, in both cases.
> 
> The retailer has Possession of the items, in case of vendor-managed inventory. 
> 
> Retailer's liability for theft and damage can be derived from the fact that a claim exists on these items (the retailer possesses items he does not own, which creates a claim). This claim can be settled either financially, or by returning the items back to the vendor (the owner). For example, kiosks selling newspapers and magazines pay the vendor for the sold newspapers, and return the unsold newspapers back to the vendor. 
> 
> In case of transportation, the trucking company has Possession of the transported items. This case is interesting because the trucking company has only limited knowledge of the content of the transported packages, so they have possession of items they do not know (and often must not know, in case of postal services). They can only track possession of the packages, not their content. 
> 
> During offline discussion with Christian we came across a third case, which illustrates a difference between possession and availability. In army units, there are often people having material responsibility (i.e. liability, custody) for certain items, that is, if something is missing in the inventory, the people with material responsibility cover the loss. For example, one of the petty officers in the fuel supply unit has material responsibility for the fuel in fuel tanks, one of the senior cooks has material responsibility for the raw materials in the kitchen store, etc. However, in practice, there are many other soldiers that can take fuel from the fuel pumps, and practically all cooks can get raw materials from the kitchen store. 
> 
> In POA terms, the petty officers with material responsibility (custody) have Possession of these items, and the other soldiers with access the store have Availability. Of course, until they take physically these items from the store, then they receive possession, and the person with material responsibility looses possession, accordingly.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/exchange/-/issues/22.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
