### ISSUE TITLE
The evolution of intents to commitments to claims to economic events

### ISSUE THREAD

**Issue by bhaugen** [valueflows/exchange#23]
- I need something.
- I cast my need on the Web as an intent (a request for something).
- I receive an offer to provide something.
- The offer comes with a requirement for providing something else in return.
- We agree. The provider of something commits to transfer something to me, and I commit to transfer something else to them. A set of reciprocal commitments.
- I transfer something else to them (an economic event, fulfilling my commitment).
- I now have a claim for them to transfer something to me.
- They transfer something to me (an economic event, satisfying my claim).

(We have already defined transfer to mean transferring some rights to a resource, so I will not repeat that with repetition of the word. Ok?)

This an extension of https://github.com/valueflows/exchange/issues/22

**Comment by gcassel** [comment]
I'd prefer to redundantly keep on pointing out "transfer rights" at this time.  To me, it feels like a really important but slippery fact.

I think the described flow of events is quite sound.   Other things could happen serially or in parallel as well, such as open discussions /  "conversations for agreement" which lead to Offers.

**Comment by ahdinosaur** [comment]
related to https://github.com/valueflows/valueflows/issues/104

**Comment by elf-pavlik** [comment]
Whenever we have IRI (in snippets I use [CURIE](https://www.w3.org/TR/curie/)) as value of property _vf:foo_ (any property other than `@id`), we can take the whole object which has same IRI as its `@id` and nest it as value of _vf:foo_ instead of that IRI. Those IRIs act as references!

> - I need something.

``` yaml
'@context': https://w3id.org/valueflows/v1
'@id': elf:ideas/a-seven-kilo-of-rolled-oats
'@type':
  - vf:Resource
  - prodont:Rolled_oats
'vf:amount':
  'qudt:unit': unit:Kilogram
  'qudt:numericValue': 7
```

> - I cast my need on the Web as an intent (a request for something).

``` yaml
'@context': https://w3id.org/valueflows/v1
'@id': elf:request/rolled-oats-for-a-month
'@type': vf:Request
'vf-:subject':
  '@id': elf:identity
  name: elf Pavlik
'schema:eligibleRegion':
  '@id': https://www.wikidata.org/entity/Q16978314
  name: Mexio City
'vf-x:object': elf:ideas/a-seven-kilo-of-rolled-oats
```

> - I receive an offer to provide something.
> - The offer comes with a requirement for providing something else in return.

``` yml
'@context': https://w3id.org/valueflows/v1
'@id': coop:proposals/oats-for-apples
'@type': vf-x:Proposal
name: 10kg bag of rolled oats to elf, in exchange for 10kg of fresh apples
'vf-x:author': dan:identity
'vf:validUntil': <a week from today>
'vf-x:promise':
  '@type': vf:Transfer
  'vf:from': coop:identity
  'vf:to': elf:identity
  'vf-x:rightsFor':
    '@id': coop:packages/63b74fa5-4acc-4a98-9a4a-b6af743cb7b9
    '@type':
      - vf:Resource
      - prodont:Rolled_oats
    'vf:amount':
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 10
    note: 10kg of rolled of oats in a bag with QR code containing IRI (this @id)
'vf-x:expectation':
  '@type': vf:Transfer
  'vf:from': elf:identity
  'vf:to': coop:identity
  'vf-x:rightsFor':
    '@id': coop:ideas/a-10-kilo-of-apples-which-elf-has
    '@type':
      - vf:Resource
      - prodont:Apple
    'vf:amount':
      'qudt:numericValue': 10
      'qudt:unit': unit:Kilogram
```

> - We agree. The provider of something commits to transfer something to me, and I commit to transfer something else to them. A set of reciprocal commitments.

``` yml
'@context': https://w3id.org/valueflows/v1
'@id': elf:commitments/apples-for-oats
'@type': vf-x:Commitment
name: 10kg of fresh apples in exchange for 10kg bag of rolled oats 
'vf-x:author': elf:identity
'vf:validUntil': <a week from today>
'vf-x:promise':
  '@type': vf:Transfer
  'vf:from': elf:identity
  'vf:to': coop:identity
  'vf-x:rightsFor':
    '@id': elf:packages/eaea06b8-2e79-40a2-be62-682df3452b3c
    '@type':
      - vf:Resource
      - prodont:Apple
    'vf:amount':
      'qudt:numericValue': 10
      'qudt:unit': unit:Kilogram
'vf-x:expectation':
  '@type': vf:Transfer
  'vf:from': coop:identity
  'vf:to': elf:identity
  'vf-x:rightsFor': coop:packages/63b74fa5-4acc-4a98-9a4a-b6af743cb7b9
```

``` yml
'@context': https://w3id.org/valueflows/v1
'@id': coop:commitments/oats-for-apples
'@type': vf-x:Commitment
name: 10kg bag of rolled oats in exchange for 10kg box of fresh apples 
'vf-x:author': sally:identity
'vf:validUntil': <a week from today>
'vf-x:promise':
  '@type': vf:Transfer
  'vf:from': coop:identity
  'vf:to': elf:identity
  'vf-x:rightsFor': coop:packages/63b74fa5-4acc-4a98-9a4a-b6af743cb7b9
'vf-x:expectation':
  '@type': vf:Transfer
  'vf:from': elf:identity
  'vf:to': coop:identity
  'vf-x:rightsFor': elf:packages/eaea06b8-2e79-40a2-be62-682df3452b3c
```

> - I transfer something else to them (an economic event, fulfilling my commitment).
> - I now have a claim for them to transfer something to me.
> - They transfer something to me (an economic event, satisfying my claim).

**TODO**
- agent relationships which show that `sally:identity` and `dan:identity` can make proposals and commitments on behalf of `coop:identity`

**Comment by elf-pavlik** [comment]
> - I transfer something else to them (an economic event, fulfilling my commitment).

``` yml
'@context': https://w3id.org/valueflows/v1
'@id': coop:transfers/2df96afe-6729-4200-b317-fc84c9a9d604
'@type': vf:Transfer
'vf-x:fulfils': elf:commitments/apples-for-oats
'vf:from': elf:identity
'vf:to': coop:identity
'vf-x:rightsFor': elf:packages/eaea06b8-2e79-40a2-be62-682df3452b3
```

> - I now have a claim for them to transfer something to me.
> - They transfer something to me (an economic event, satisfying my claim).

``` yml
'@context': https://w3id.org/valueflows/v1
'@id': coop:transfers/baf9d073-c13e-4728-8d55-a195dd9b2c07
'@type': vf:Transfer
'vf-x:fulfils': coop:commitments/oats-for-apples
'vf:from': coop:identity
'vf:to': elf:identity
'vf-x:rightsFor': coop:packages/63b74fa5-4acc-4a98-9a4a-b6af743cb7b9
```

**TODO**
- agreements on delivery (_vf:Transportation_), so far the actual apples and oats haven't moved even an inch

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/exchange/-/issues/23.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
