### ISSUE TITLE
define Warranty

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/exchange#24]
In recent conversations warranty occurred couple of times, it seems to fit this repo as one of agreements we make. We could add variant to personal computer use case which has warranty.

seeAlso: http://gs1.org/voc/WarrantyPromise

**Comment by bhaugen** [comment]
Warranty seems like a great concept to delegate to some other vocab in detail (like some vocab that is working on contracts, there must be one...?), although it fits awkwardly into @gcassel 's agreements theme.

It's basically part of a contract, and a contract is a set of commitments. But if we get too deep into contracts, we will never get out. See http://research.microsoft.com/en-us/um/people/simonpj/Papers/financial-contracts/contracts-icfp.htm

**Comment by danalexilewis** [comment]
@bhaugen I totally agree. Warranty/contract feels like information that needs to be attached to a resource and exchanged but does not need to be represented in the vf abstraction. 

A lease may be another example of this - where say a car/house is leased long term. There would an exchange, but the resources would have conditional contracts with them.

**Comment by elf-pavlik** [comment]
AFAIK warranty often includes a promise (vf:Claim ? #22 ) for repair service valid in certain period of time. I think we may want to represent those services as resources https://github.com/valueflows/resource/issues/15 and in transfer bundle them together with the Product.

Actually on Monday I might capture how it works in [Dental Care](https://github.com/valueflows/valueflows/blob/master/use-cases/dental-care.md) use case (warranty on Service not a Product)

**Comment by bhaugen** [comment]
Warranty is a complex set of commitments (promises) and potential economic events. I'm just saying that some people we know and could connect to as needed are working seriously on that whole territory. And it's deep. So I'm happy to follow their lead for the time being.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/exchange/-/issues/24.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
