### ISSUE TITLE
representing Tax

### ISSUE THREAD

**Issue by ahdinosaur** [valueflows/exchange#26]
from https://github.com/elf-pavlik/currency/issues/3#issuecomment-217309374,

> I missed mentioning Taxes, where do we work on dealing with [VAT](https://en.wikipedia.org/wiki/Value-added_tax)?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/exchange/-/issues/26.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
