### ISSUE TITLE
agreement on delivery of transfered resource

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/exchange#27]
#25 mentions very specific type of delivery 'payment method' (usually digital). I think vf:Transfer (also used for vf:Exchange) needs a way to specify agreement on delivering the resource rights over we transfer.

Some examples from Open Food Network
- https://openfoodnetwork.org/user-guide/hubs-set-up-guide/shipping-methods/
  - https://openfoodnetwork.org/payment-methods/

**Comment by bhaugen** [comment]
If you look at the Conversation for Action protocol, it covers agreements about whether the reciprocal flow has happened. 
![cfa](https://github.com/valnet/exchange/raw/master/images/CfA_state_machine.png)

**Comment by elf-pavlik** [comment]
The delivery vf:Transportation (process/action/event) happens independently of vf:Transfer (action/event) For example:
1. Amanda exchanged rights to 20kg of apples stored in her cellar with Sam for 20kg of mangos stored in his shed.
2. They **agreed** that Sam will take care of (responsibility for) both way delivery
3. Sam decided that he will ask Veronica to do both ways delivery as part of her bike shipping service offer.
4. Before delivery
   - Sam owns 20kg of apples located in Amanda's cellar
   - Amanda owns 20kg of mangos located in Sam's shed
5. Veronica does delivery
   - she picks 20kg of mangos **already owned** by Amanda from Sam's shed and travels to her by bike.
   - she leaves mangos in Amanda's cellar and picks up apples **already owned** by Sam from there
   - she finishes work for today, taking apples owned by Sam to her home, her friends arrive at night from the party and eat all the apples
6. Sam understands the situation and he asks Amanda to don't worry about it and they all move on with their lives.

**Comment by bhaugen** [comment]
> she picks 20kg of mangos already owned by Amanda from Sam's shed and travels to her by bike.
> she leaves mangos in Amanda's cellar and picks up apples already owned by Sam from there

That's [FOB origin](http://www.transportationinsight.com/blog/2012/06/f-o-b-mean/).

**Comment by elf-pavlik** [comment]
![fob-destination](https://cloud.githubusercontent.com/assets/876431/17540730/3ecaa708-5e7e-11e6-99b1-45b3276a409e.jpg)
![fob-origin](https://cloud.githubusercontent.com/assets/876431/17540731/3ed43462-5e7e-11e6-9fde-e3416d24e023.jpg)

those illustrations might overlay in interesting ways with

![transfer&transportation](https://docs.google.com/drawings/d/1KcajKeandUHrB3TINyjm3-IP8uGKTnxR66MFuBYjwhs/pub?w=747&h=317)

I think in defining vf:Transportation we should keep in mind that it works as a process and not atomic event. vf:Transfer can work as atomic event and once again I want to emphasise that we should treat vf:Transfer differently from vf:Process!

**Comment by bhaugen** [comment]
Transportation will often involve an exchange of transportation service (Freight) for something. E.g. from that same reference:
- F.O.B. Origin, Freight Collect:
- F.O.B. Origin, Freight Prepaid:
- F.O.B. Destination, Freight Collect:
- F.O.B. Destination, Freight Prepaid:

**Comment by bhaugen** [comment]
I think in most cases people want to see all the reciprocal commitments and events wrapped up in the same exchange, but the transportation process is usually the transportation provider's responsibility and is encapsulated in their context.

**Comment by elf-pavlik** [comment]
Some transportation services work as gift http://sustainablepost.org/about-lightfoot
One could send a piece of jewellery as a gift using lightfoot. We have only vf:Transfer and vf:Transport but no vf:Exchange at all.
At the same time I agree that if we need to express vf:Exchange we need to capture all the specific commitments that agents care about and **agreed** on.

**Comment by elf-pavlik** [comment]
Maybe agreement can in simplest case just specify that someone promises (makes commitment) to pick up the resource from somewhere or drop it off to somewhere? I shouldn't matter If an agent does the transportation oneself or delegates it to 3-rd party.

**Comment by bshambaugh** [comment]
The third party would represent an interaction with another agent, but it
may not be important to the interaction with the first two agents.

-Brent Shambaugh

Website: bshambaugh.org

**Comment by bshambaugh** [comment]
At the same time I agree that if we need to express vf:Exchange we need to
capture all the specific commitments that agents care about and _agreed_
on.       <<---out of the loop a bit, but this sounds like a tall order

-Brent Shambaugh

Website: bshambaugh.org

**Comment by bhaugen** [comment]
> At the same time I agree that if we need to express vf:Exchange we need to
> capture all the specific commitments that agents care about and _agreed_
> on.       <<---out of the loop a bit, but this sounds like a tall order

If the agents involved execute a defined protocol (e.g. conversation for action, CfA, as in the diagram above), it's not very tall. One of our jobs in VF will be to specify that and possibly some other protocols in enough detail to be implementable. CfA has been implemented many times, and is already fairly well specified.

**Comment by elf-pavlik** [comment]
from: http://schema.org/DeliveryMethod

> Commonly used values:
-    http://purl.org/goodrelations/v1#DeliveryModeDirectDownload
-    http://purl.org/goodrelations/v1#DeliveryModeFreight
-    http://purl.org/goodrelations/v1#DeliveryModeMail
-    http://purl.org/goodrelations/v1#DeliveryModeOwnFleet
-    http://purl.org/goodrelations/v1#DeliveryModePickUp
-    http://purl.org/goodrelations/v1#DHL
-    http://purl.org/goodrelations/v1#FederalExpress
-    http://purl.org/goodrelations/v1#UPS

from: http://schema.org/ParcelService

> Commonly used values:
-    http://purl.org/goodrelations/v1#DHL
-    http://purl.org/goodrelations/v1#FederalExpress
-    http://purl.org/goodrelations/v1#UPS

IMO http://schema.org/OnSitePickup + some generic 'drop off' could give a good starting point. Later if an agent responsible for transportation wants to delegate the 'pick-up' or 'drop-off' to another agent, they can make independent agreement.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/exchange/-/issues/27.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
