### ISSUE TITLE
Food Stamp (concrete example)

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/exchange#3]
Following up on https://github.com/openvocab/ovn/issues/17#issuecomment-133706715

@zippy said:

> Monetary currencies are just a generalized
> issued tokens, whereas movie tickets and postage stamps have a more limited
> use.  Then, under "Issued Tokens" you would use a Unit that matches what
> they are issued for, with monetary currencies in part being created for the
> purpose of having a unit, i.e. they create their own unit, whereas the unit
> for movie tickets is "seat" and postage stamps is a monetary currency.

I would like to exercise modeling of _FoodStamp_. How would you currently model an Offer(s) which gives choice of receiving certain amount of food after 'paying' for it either with $$$ or food stamps?

**Comment by bhaugen** [comment]
FoodStamp: great use case.

**Comment by elf-pavlik** [comment]
I failed to get started with [Web Currencies CG](https://www.w3.org/community/webcurrencies/) and it got deactivated. We could try to restart it and focus it on Linked Data definitions for all kind of different currency types. I even started collecting there few years ago [couple of examples for shares of assets](http://www.w3.org/community/webcurrencies/wiki/Assets_Shares)

Following thinking I refer to as [Polyeconomy](http://polyeconomy.info/) (i need to republish that website). Preferably each Offer/Demand allows _negotiation_ with use of multiple types of _currencies_. This enables each pair of _agents_ to chose which ones they prefer to use between themselves, and different pairs will end up settling on use of different currency types! I tried to illustrate it with concrete use case of ridesharing on [those slides](https://docs.google.com/presentation/d/1RshtXUDXta_CwSjPXjCZlxsmXCSedaRCaBwaXGap8SE/edit?usp=sharing)

**Comment by fosterlynn** [comment]
> Preferably each Offer/Demand allows negotiation with use of multiple types of currencies. This enables each pair of agents to chose which ones they prefer to use between themselves, and different pairs will end up settling on use of different currency types! 

Agree. Here is a screen shot from a reply to an offer in WeZer, in the use case we are working on in Madison (MAN is their network's internal currency):
![manreply](https://cloud.githubusercontent.com/assets/3776081/9448894/d3a9538a-4a64-11e5-983f-b97e08462092.png)

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/exchange/-/issues/3.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
