### ISSUE TITLE
Use case: vendor managed inventory

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/exchange#30]
Creating this to specifically look at how a vf:Transfer of a resource that is not serialized or identified in any way that people care about could work. We agree that if a UUID or some unique identifier can be created, then resources can be tracked through a vf:Transfer, even if the @id changes.  We are discussing how this might work if there is no logical or agreed upon unique identifer to a resource, such as a serial number.

Experimental yaml to come.....

[edit: .... or not.....]

**Comment by gcassel** [comment]
Dunno if this idea progressed anywhere-- if so, links appreciated!

Anyway, I think this subject can be effectively addressed through simple modular conventions for names and relationships, *as long as* the (resource) sending and receiving agents can mutually agree upon the names and relationships involved.  

For example, I think it'd be very helpful for a vf community to enable a mutually verified report such as "Fred gifted his red ruler to Joe" or  "Emily sold her red ruler to Joe for $1.38".    

A wide variety of exchanges can be usefully tracked in such ways, without applying unique identifiers to the exchanged resources.  In fact, we do this frequently with currency and other fungible commodities.   Y'know, no one's gonna track *which* 1 dollar or which 38 cents Emily received from Joe!   It's simply not part of current systems.   (Of course, that does create risks, but this isn't the place for discussing centrally printed currencies versus mutual credit, counterfeit, etcetera.)

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/exchange/-/issues/30.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
