### ISSUE TITLE
Mutual credit systems

### ISSUE THREAD

**Issue by bhaugen** [valueflows/exchange#4]
Maybe a different view of some exchange issues, as well as maybe #2:

"Intertrading is based on the idea that if neighbouring systems are both using 'LETS' units and these units are all equivalent to the national currency, then the units can simply be exchanged. However simply connecting trading between systems in this way - effectively merges two Mutual Credit Systems and undermines the community based characteristic of the currency created within each system. Mutual Credit Systems work as networks where the accounts always add up to zero."

"Interlinking... is a modified version of intertrading. It involves systems having accounts in each other's systems and does overcome the difficulty of money moving (intertrading) as it ensures that the accounts in each system continue to add up to zero. However, interlinking introduces another - arguably more serious problem, transferring committment by the individual to that of the system as a whole. 
For a Mutual Credit System to be sustainable, accounts have to be backed by personal commitment."

"MultiLETS allows transactions to be recorded in any of the subsystems of which the buyer and seller have accounts, or in the Registry system if a shared local system cannot be found.  Thus all of the systems remain in balance, while ensuring individual committment.  Also, an even greater goal, the gravitation of money to the locality, is ensured.  The local money has its greatest use-value in the local system, simply because it is easier to spend one's dollars closer to home. "

From http://www.complementarycurrency.org/helpdesk/linking_mutual_credit.html

**Comment by bhaugen** [comment]
[Matthew Slater](http://matslats.net/) says:
"The model I am pushing for is the second one. I don't see it as a problem that credit risk is transferred from the individual to the community, although it does mean that good governance is important. This is also how CES works.
"The third model, multiLETS is quite difficult precisely because units do stray from home where their meaning and value is less understood. Also it requires I think more complex technology to enable different systems to hold each other's currencies."

He offers "an introductory blog considering the economics of joining up mutual credit systems":
http://matslats.net/credit-commons-better-than-bitcoin

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/exchange/-/issues/4.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
