### ISSUE TITLE
Karma Pass

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/exchange#5]
I started describing it here
https://github.com/hackers4peace/polyeconomy.info/wiki/Karma-Pass

Some relevant conversation about ticket / participation activity in https://github.com/schemaorg/schemaorg/issues/134#issuecomment-93369527

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/exchange/-/issues/5.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
