### ISSUE TITLE
Job Offer & Job Board

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/exchange#7]
Looks like a very common feature which people should appreciate to make portable, since many offers could appear on multiple job boards 
- http://www.fossjobs.net/
  - http://crosscloud.org/jobs/ | http://www.fossjobs.net/job/6911/devopsbackend-engineer-at-crosscloud/ & http://www.fossjobs.net/job/6910/front-end-developer-at-crosscloud/
  - https://www.sharetribe.com/jobs.html | http://www.fossjobs.net/job/6921/ruby-developer-at-sharetribe/
- https://jobs.ouishare.net/
- http://www.collaborativeconsumption.com/job-board/
- http://jobs.makesense.org/

On funny side jobs.ouishare.net runs on sharetribe software but its developers can't even syndicate their self hosted job offer there :dizzy_face:

**Comment by pmackay** [comment]
Worth scanning http://blog.memespring.co.uk/2015/07/02/open-standards-for-job-vacancies/ which is related.

**Comment by Em-AK** [comment]
I'm ready to talk about this with you @elf-pavlik 
The software I wrote for http://jobs.makesense.org/ is the most basic you could think of. Despite that people use it !
I owe them some improvements ;)

**Comment by fosterlynn** [comment]
Good use case...  And welcome @Em-AK !

@elf-pavlik how do you want to start?

**Comment by elf-pavlik** [comment]
@fosterlynn we will take a bus together with @Em-AK Paris -> Berlin on Dec 11th and will take opportunity to discuss it IRL.

I would like to add to people profiles examples of skills and types of work one can do. Than if job offers use same identifiers (eg. wikidata) it can allow filtering offers by how they match your capabilities.

Since we will go together for [Open Food Network hackweek](http://community.openfoodnetwork.org/t/hackathon-to-attract-european-developers/386) we can start listing types of work which participants will do there.

Programming, in particular:
- Ruby on Rails https://www.wikidata.org/wiki/Q190478
- AngularJS https://www.wikidata.org/wiki/Q2849803

etc.

**Comment by bhaugen** [comment]
I recognize that job listings often specify particular technologies, but IRL many people who have been around for awhile can pick up a new language pretty quickly and may have more important attributes to offer. (Speaking as an old fart.)

**Comment by elf-pavlik** [comment]
I also see place for broader/narrower attributes
- OOP - https://www.wikidata.org/wiki/Q79872
- REST - https://www.wikidata.org/wiki/Q749568

I think job offer could aggregate types of work from inputs to all the processes, to which this person would contribute to. I also liked what you showed me in NRP, how various types of work performed show up in person's profile. But from job offer perspective, aggregating types of work on input to all the processes seems like something most working groups would do.

**Comment by bhaugen** [comment]
> aggregating types of work on input to all the processes seems like something most working groups would do.

Aggregating all the types of work from all the processes connected to a context agent should be pretty easy to do with the VF vocab. Might make a good demo...? We (or should I say, @fosterlynn ) could generate it from nrp.sensorica.co

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/exchange/-/issues/7.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
