### ISSUE TITLE
Transfer vs. Exchange & tracking vs. accounting

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/exchange#8]
conversation from gitter

> elf-pavlik 17:30
> @bhaugen would you see conversations about Commitment fitting exchange repo?
> bhaugen 18:49
> @elf-pavlik - yes. Conversations for action is all about making commitments, fulfilling them, and then evaluating the results.
> Might not be clear yet in the README
> CfA does not need to be about exchanges, though. Could also be about planning a process to create something. Or having a party.
> elf-pavlik 18:55
> If someone works on something (this work goes as input in the process), do you consider it and exchange?
> working on something sounds like a Service to me, eg. fixing 3 open bugs which took me 3 hours
> bhaugen 19:01
> That's a good question. We're about to each lunch, and I will discuss with Lynn how to answer it without being confusing.
> And then I will answer it, but might want to write something at more length, with some diagrams.
> elf-pavlik 19:02
> bon appétit 
> for tangible items, i guess whatever happens within a single 'Inventory' doesn't involve an Exchange step, single 'Inventory' in sense of 'owned' by same agent...
> @elf-pavlik created place for discussion about Inventory (and sub inventories) in valueflows/resource#1
> bhaugen 19:26
> @elf-pavlik - are you sure this conversation belongs in inventory rather than exchange?
> elf-pavlik 19:28
> where does resources belong to?
> right, you can link each resource directly to agent and skip inventory all together
> bhaugen 19:28
> resources could be inventoried or not
> if you inventory work, it is on a calendar.
> if you inventory tires, it is in a warehouse
> elf-pavlik 19:29
> i assume that if resource doesn't change an owner than no exchange happens?
> bhaugen 19:29
> work is different from other things
> yes, if a resource doesnt change an owner, then no exchange
> but that gets tricky, when people buy and sell rights
> work creates things
> so back to your question, yes there are exchanges around work, but then there are sub-questions about timing, and what is actually being exchanged
> elf-pavlik 19:31
> and no one own's agents or work their do, so each work which one may want to account for comes with an exchange...
> bhaugen 19:31
> so for example if you are a salaried worker, you exchange your labor time per week
> the work you do in a process is not subject to another exchange
> In general, people pay for labor time, but then active work happens during that time, and is different from the labor time
> say I am a skilled potter.
> I turn bowls out of clay.
> elf-pavlik 19:34
> If I perform work which contributes to a resource which I don't own - this causes an exchange (at least one way of looking at it)
> bhaugen 19:34
> my hands and arms and legs and their accumulated muscle memory and my mental skills are all employed in turning the bowl.
> all of those accumulated skills are what someone pays for if they pay me to turn a bowl.
> If they just buy a bowl that I made, then all of those skills and that labor are incorporated in the bowl. So there is no separate exchange for the labor.
> elf-pavlik 19:37
> So you worked on a bowl which you own - so far fits my statement above - no exchange so far
> bhaugen 19:36
> In sensorica, when I contribute work to a process, and the ultimate results of the chain of processes brings in some income,
> then the value equation floats some of that back to me, and the exchange for my labor time happens then.
> elf-pavlik 19:38
> can we keep those two flows distinct (while still can reference each other when desired) ?
> bhaugen 19:38
> so there's the labor time, the actions of physical and mental work, and the results (what was created)
> which two flows do you mean?
> elf-pavlik 19:39
> 1) i contribute some work toward a resource which i don't own myself e.g. collectively own resource (one way exchange)
> 2) i receive 3 months later a rideshare from someone who knew about work i have done and wanted to express gratitude, even though i didn't expect anything from that person (second one way exchange)
> we can optionally link those two exchanges to each other but don't have to since they stay a distinct information entities
> bhaugen 19:41
> I got no problem with either of those
> if you contribute some work to a resource which is collectively owned and collectively used and does not enter into commerce, then you are operating in a different economic system.
> which is a good place to be.
> let's take the bowl.
> the work, the physical and mental labor, the use of embodied skills, is the same in any of the situations I will list:
> the potter makes and sells the bowl
> the potter works for a company that pays by the hour and the company sells the bowl
> the potter works for a communical kitchen where the bowl is used to knead bread dough
> but the relationships among the agents are different in each of those situations
> and the details of the exchanges are different.
> i
> elf-pavlik 19:45
> what do you think about making accounting orthogonal to modeling of real world events involved in all hose scenarios above
> bhaugen 19:45
> In the last situation, the communal kitchen, you could say that the potter gets bread, or a community to live in, but it's a little churlish to even mention exchange
> accounting is orthogonal
> that's the difference between the forces of production and the relations of production
> we are, however, embedded in a system of commodity exchange, and will need to work our way out of it
> and not all at one time, unfortunatel
> y
> so the potter and the communal kitchen is a lot like your collectively owned resource and rideshare some months later
> they are all happening in a different economic system
> different relations
> elf-pavlik 19:51
> can we try to clarify when exchange happens and when not?
> bhaugen 19:51
> I would start by example.
> elf-pavlik 19:51
> in terms of 'agent owns a resource'
> 'agent contributes work to a resource'
> bhaugen 19:51
> in both cases, what happens to the resource?
> agent owns a resource and uses it
> agent owns a resource and sells it
> only exchange in the second case
> agent contributes work to a resource:
> elf-pavlik 19:53
> agent donates a resource
> agent borrows/lends a resource
> bhaugen 19:53
> agent donates a resource: a tricky case
> @elf-pavlik back in 15min
> bhaugen 19:53
> agent borrows or lends a resource: could be barter, could be mutual credit
> elf-pavlik 20:00
> if agent sells resource differs from agent donates resource it sounds like we don't have accounting orthogonal here
> bhaugen 20:01
> Agent donates resource: could be for the good of the community, could be for a tax break, could be for reputation points.
> elf-pavlik 20:01
> for me in both sell and donate ownership changes (permanently)
> bhaugen 20:01
> but I don't understand "we don't have accounting orthogonal here"
> elf-pavlik 20:02
> what else makes 'agent sells resource' different from 'agent donates resource' ?
> bhaugen 20:02
> agent sells resource and gets something in return (that is, an exchange).
> agent donates resource: the ownership changes, but might or might not be an exchange.
> elf-pavlik 20:03
> (two way exchange || two one way exchanges which depend on each other - conditional)
> donate (one way exchange - unconditional)
> bhaugen 20:03
> I don't think one-way is an exchange.
> but it depends on your definition.
> If a change of ownership is an exchange, then it is.
> elf-pavlik 20:04
> I would like to try syncing them and documenting better
> bhaugen 20:04
> I think of exchange as a trade, that is, two-way.
> fosterlynn 20:05
> you don't need an exchange to change ownership, a transfer event can do that, for one resource
> elf-pavlik 20:05
> How do you model flows which use gifts? We don't even need one way exchanges
> fosterlynn 20:05
> (although I do create an exchange in NRP for one way transfers, possibly incorrectly)
> bhaugen 20:05
> I would reserve the word exchange for a trade, two-way
> elf-pavlik 20:06
> doesn't it introduce accounting ?
> bhaugen 20:06
> two-way introduces accounting
> elf-pavlik 20:06
> making transfers conditional
> bhaugen 20:06
> yes, if I understand what you mean
> but then it also depends on what you mean by accounting.
> elf-pavlik 20:07
> ok, so on a level without accounting we deal with Transfer
> fosterlynn 20:06
> one way introduces accounting in that a resource was added to inventory (in the case of a donation of something), true?
> bhaugen 20:07
> the guy that does energy accounting for ecosystems also calls it accounting
> elf-pavlik 20:07
> good point!
> bhaugen 20:07
> the base is counting
> but from a business accounting viewpoint, if it's not an economic event (a significant change in a resource that they own), it's not accounting.
> and then if they gave something up, they need to know, what did they get for that in return?
> elf-pavlik 20:10
> do you have any experience with chain barter? eg. http://edgeryders.eu/en/makerfox/open-sourcing-network-barter
> bhaugen 20:09
> if they haven't gotten it yet, they got it coming
> I understand the concept, but have no experience
> we're learning about mutual credit systems, which are a more flexible version of the same thing
> elf-pavlik 20:10
> can we find distinction between tracking and accounting ?
> bhaugen 20:10
> by example:
> a steer was butchered
> the cuts of meat went to many places
> elf-pavlik 20:11
> i same agent owns two 'inventories' and resources move between them - do we go into accounting or just tracking
> bhaugen 20:11
> some of them went into sausage
> @elf-pavlik ouch! gets bloody here 
> bhaugen 20:11
> later on somebody gets sick
> they need to track the sausage back to the source animals
> not the same as accounting, but uses some of the same information
> just much more detailed
> elf-pavlik 20:12
> you used word track
> bhaugen 20:12
> actually, i think that is tracing
> but i get confused myself
> i think tracing goes back to the source
> tracking goes forward to the destinations
> elf-pavlik 20:14
> if we consider planet earth an agent and follow "Earth doesn't belong to us, we belong to Earth" - do we just do tracking or go into accounting
> bhaugen 20:13
> moving resources between locations does not show up in accounting, but it does show up in counting and tracking
> I think accounting assumes systems of exchange
> elf-pavlik 20:15
> makes sense to me
> bhaugen 20:14
> but the guy that does ecosystem accounting thinks exchanges of energy
> elf-pavlik 20:15
> but I would like to keep tracking and accounting orthogonal if possible 
> bhaugen 20:15
> what does that mean to you?
> elf-pavlik 20:16
> that we can agree on how we keep track on things, but can disagree on how we account for them
> bhaugen 20:15
> sure
> unless we are doing energy accounting
> then we need to be more strict
> example of disagreeing on how we account for something?
> elf-pavlik 20:17
> energy in a sense of electricity in a grid eg. http://geni.org/
> bhaugen 20:17
> is geni an example of energy accounting or disagreeing on how we account for something?
> elf-pavlik 20:18
> i see possibility of tracking electricity (using meters) but still keeping accounting separate from that
>  @bhaugen
> moving resources between locations does not show up in accounting, but it does show up in counting and tracking
> I think accounting assumes systems of exchange
> bhaugen 20:18
> the energy accounting in an ecosystem people are tracking the flows of resources in a living ecosystem, not accounting for money, or electricity in a grid
> but yes, tracking electricity could be done (and is done) separately from accounting.
> balancing the grid, for example
> elf-pavlik 20:20
> can we try to document nuances of Exchange vs. Transfer and accounting vs. tracking?
> bhaugen 20:20
> http://www.cep.ees.ufl.edu/emergy/about/research_agenda.shtml
> elf-pavlik 20:21
> in a sense of how we define them and distinguish them in context of vf: work
> bhaugen 20:21
> we should do that, but it's a deep topic
> https://en.wikipedia.org/wiki/Emergy
> are we getting anywhere in this conversation?
> elf-pavlik 20:22
> if I just work with Transfer and tracking I don't need anything from https://github.com/openvocab/exchange ?
> bhaugen 20:22
> might not
> depends on what you are trying to do
> Lynn says we should get back to work on agent...
> elf-pavlik 20:23
> where we work on Transfer and tracking than? process repo?
> fosterlynn 20:23
> i think the exchange repo should probably include transfer events that are not part of an exchange.....
> or we could start an event repo?
> bhaugen 20:23
> I don't think process is the place

**Comment by bhaugen** [comment]
@ahdinosaur @almereyda did you get anything out of that (above)?

**Comment by ahdinosaur** [comment]
i got that we should document any and all use cases (e.g. [relationships with agents and resources](https://github.com/valueflows/agent/blob/master/Properties.md)) as markdown files in a `use-cases/` directory in the repo of the domain we think is most related. i reckon if we lay everything out, we'll have a clearer picture of the minimal vocab that can support what we need, especially because i want us to avoid what other vocabs do in creating new terms for new use cases.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/exchange/-/issues/8.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
