### ISSUE TITLE
vf:reciprocal 

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/exchange#9]
In context of Exchange which involves certain Transfer in 'one direction' and another 'in opposite direction'. We could use property like vf:reciprocal to link those two together.

**Comment by bhaugen** [comment]
I like it.

**Comment by elf-pavlik** [comment]
In 10 years one can also send one of the contributors to this vocab a Gift and mark it as vf:reciprocal to PullRequest for this project which this person (receiving gift) contributed in distant past :smile:

**Comment by bhaugen** [comment]
clicked wrong button accidentally, did not mean to close.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/exchange/-/issues/9.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
